### ISSUE TITLE
Regarding the number of patterns used for calibration and the camera models that can be calibrated

### ISSUE THREAD

**Issue by dongshengLiu** [amy-tabb/calico#4]
Thanks for your work，I have two questions:
1）If it ensures that all cameras can see the calibration pattern, can I use only one calibration pattern ?
2）Does calico only support pinhole camera models?

**Comment by amy-tabb** [comment]
1) yes, if all cameras can see the pattern, or if your cameras can see the pattern by moving it, grabbing an image, moving it, to form a chain of images where neighbor cameras can see the pattern, you only need one pattern. (I hope this is not confusing)
2) Yes, calico assumes a pinhole camera model.  It uses the OpenCV camera calibration functions for intrinsic camera calibration.  [Here's](https://docs.opencv.org/4.5.0/d4/d94/tutorial_camera_calibration.html) the basics from the OpenCV perspective.

**Comment by dongshengLiu** [comment]
> 1. yes, if all cameras can see the pattern, or if your cameras can see the pattern by moving it, grabbing an image, moving it, to form a chain of images where neighbor cameras can see the pattern, you only need one pattern. (I hope this is not confusing)
> 2. Yes, calico assumes a pinhole camera model.  It uses the OpenCV camera calibration functions for intrinsic camera calibration.  [Here's](https://docs.opencv.org/4.5.0/d4/d94/tutorial_camera_calibration.html) the basics from the OpenCV perspective.

Thanks very much for your reply !
